### ISSUE TITLE
Need more F's

### ISSUE THREAD

**Issue by pasadores** [antonioalfa22/EFE-Forms#21]
When the respuestaRepository of respuestaRepository.js gets all the responses, it doesn't include as many F's as it should be. For example, today I searched for F's and it just returns 42 F's, as it should return more than 80. 

This is a really annoying behaviour and I hope you could fix it, nowadays the app its not usable anymore.

**Comment by antoniopaya22** [comment]
Aquí las tienes:

# fffffffffffffffffffffffffffffffffffffffffff
